services:
 nest-app:
  build:
    context: .
    dockerfile: ./Dockerfile
  ports:
    - '8080:8080'
  volumes:
    - ./D:\my-app\nest-study:/user/app
 db:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: YUGE1858382..*
    MYSQL_DATABASE: nest_study
  ports:
   - "3308:3308"